kind: ConfigMap
apiVersion: v1
metadata:
  name: wireguard-configmap
  namespace: wireguard
  labels:
    app: wireguard
data:
  wg0.conf: |
    [Interface]
    Address = 10.8.0.1/24
    ListenPort = 51820
    PostUp = wg set wg0 private-key /etc/wireguard/privatekey && iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
    PostDown = iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

    [Peer]
    #AG20J
    PublicKey = aiw58TEhWgNNUghRXiMot1Kjm2hhoPYWg5aeCBx/kmc=
    AllowedIPs = 10.8.0.2/32    
    
    [Peer]
    #XRN10P
    PublicKey = voDNEW576vuHRaG9GSTrJMMpS1FrEAQCo0jnkRQyGkU=
    AllowedIPs = 10.8.0.3/32