apiVersion: v1
kind: Pod
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:
  initContainer:
  - name: init
    image: busybox:
    command:
        - sh
        - -c
        - |
          echo $(wg genkey) | tee /etc/wireguard/private.key | wg pubkey > /etc/wireguard/public.key
          ID=$(echo $(date +%s%N)$(cat /var/lib/dbus/machine-id) | sha1sum)
          cat > /etc/wireguard/wg0.conf << EOF
          [Interface]
          PrivateKey = $(cat /etc/wireguard/private.key)
          Address = 10.8.0.$PEER/24, $(echo fd${ID:0:2}:${ID:2:4}:${ID:6:4}::$PEER/64)
          ListenPort = 51820
          SaveConfig = true
          EOF
    env:
        name: PEER
        value: 1
  containers:
  - name: wireguard
    image: ghcr.io/linuxserver/wireguard
    envFrom:
    - configMapRef:
        name: wireguard-configmap 
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - SYS_MODULE
      privileged: true
    volumeMounts:
      - name: wg-config
        mountPath: /config
      - name: host-volumes
        mountPath: /lib/modules
    ports:
    - containerPort: 51820
      protocol: UDP
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  volumes:
    - name: wg-config
      persistentVolumeClaim:
        claimName: wireguard-pv-claim
    - name: host-volumes
      hostPath:
        path: /lib/modules
        type: Directory
