kind: Service
apiVersion: v1
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:

  #LB for EKS might not be supported over UDP. 
  #type: LoadBalancer
  #ports:
  #- name: wg
  #  protocol: UDP
  #  port: 51820
  #  targetPort: 51820
  type: NodePort
  ports:
  - name: wg
    protocol: UDP
    port: 51820
    targetPort: 51820
    nodePort: 31820
  selector:
    app: wireguard